version: "3.8"
services:
    kafka-server2:
        restart: on-failure:5
        build: 
            context: .
        container_name: kafka-server2
        ports:
            - 9092:9092
            - 2181:2181
        tty: true
        stdin_open: true
        volumes:
            - ./:/app/
        # environment:
        #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        #     - ALLOW_PLAINTEXT_LISTENER=yes
        #     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
        #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
   