version: "3.8"

networks:
  default:
    name: mynet
    driver: bridge

services:
    zookeeper:
        build: 
            context: .
        container_name: zookeeper
        command: sh -c '/kafka/bin/zookeeper-server-start.sh /kafka/config/zookeeper.properties'
        ports:
            - 2181:2181

    kafka:
        build: 
            context: .
        container_name: kafka
        command: sh -c '/kafka/bin/kafka-server-start.sh /kafka/config/server.properties --override zookeeper.connect=zookeeper:2181 --override log.retention.hours=1'
        ports:
            - 9092:9092

    topics:
        build: 
            context: .
        container_name: topics
        command: sh -c './create_topics.sh'
        depends_on:
            - zookeeper
            - kafka

    development:
        build: 
            context: .
        container_name: dev
        tty: true
        depends_on:
            - zookeeper
            - kafka
            - topics
        volumes:
            - .:/app